# Generated by Django 4.2 on 2024-12-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatFin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NowExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expe', models.PositiveIntegerField(default=0)),
                ('Total_money', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameL', models.TextField()),
                ('minlvl', models.PositiveIntegerField()),
                ('maxlvl', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameQu', models.CharField(max_length=128)),
                ('comments', models.TextField(blank=True, null=True)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameff', models.TextField()),
                ('desc', models.TextField()),
                ('Income', models.BooleanField(default=None)),
                ('count', models.BigIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trak.catfin')),
            ],
        ),
    ]
