# Generated by Django 4.2 on 2024-11-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameQu', models.CharField(max_length=128)),
                ('comments', models.TextField(blank=True, null=True)),
                ('exp', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
