# Generated by Django 4.2 on 2024-12-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NowExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expe', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameL', models.TextField()),
                ('minlvl', models.PositiveIntegerField()),
                ('maxlvl', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameQu', models.CharField(max_length=128)),
                ('comments', models.TextField(blank=True, null=True)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
