# Generated by Django 5.1.3 on 2024-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
