# Generated by Django 4.2 on 2024-11-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0002_quest_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expe', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameL', models.TextField()),
                ('maxlvl', models.PositiveIntegerField()),
                ('nowExp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trak.nowexp')),
            ],
        ),
    ]
