# Generated by Django 4.2 on 2024-11-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0003_nowexp_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameL', models.TextField()),
                ('maxlvl', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
