# Generated by Django 5.1.3 on 2024-11-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0004_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lvls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('minExp', models.PositiveIntegerField()),
                ('maxExp', models.PositiveIntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('exp', models.PositiveIntegerField()),
            ],
        ),
    ]
