# Generated by Django 4.2 on 2024-11-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0004_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='minlvl',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
