# Generated by Django 4.2 on 2024-12-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0008_nowexp_total_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='Name_F',
            new_name='name_f',
        ),
    ]
