# Generated by Django 4.2 on 2024-12-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0010_rename_name_f_finance_namef'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default='2001-1-1 10:30'),
            preserve_default=False,
        ),
    ]
